# Generated by Django 4.2 on 2026-03-01 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('document', models.FileField(blank=True, null=True, upload_to='tender_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_tender', to='bids.bid')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
