# Generated by Django 5.2.10 on 2026-03-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vendorprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='trust_score',
            field=models.IntegerField(default=100),
        ),
    ]
