# Generated by Django 5.2.10 on 2026-03-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_bid_is_winner_alter_bid_proposal_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='is_winner',
        ),
        migrations.AlterField(
            model_name='bid',
            name='proposal_document',
            field=models.FileField(blank=True, null=True, upload_to='bids/'),
        ),
    ]
